### ISSUE TITLE
My portfolio link is outdated

### ISSUE THREAD

**Issue by p32929** [umihico/PortfolioHub#47]
Hello, thanks for listing our portfolios. BTW, here my old portfolio is listed. Can I remove the old one and list my new one?

My old portfolio was: https://p32929.github.io/Portfolio/
My new portfolio: https://p32929.github.io/

Thanks :)

**Comment by umihico** [comment]
Thank you for issuing. You made me realize my current code doesn't fetch everything properly. I'll fix and then your new portfolio will be updated in my website.

**Comment by p32929** [comment]
Thanks :)

**Comment by umihico** [comment]
Hi I confirmed your new one is properly listed. While your old one still has the hashtags #personal-website or #portfolio-website, my current project keep both listed. To remove, I need to implement opt-out function for you and some others who don't like my website. It'll take time a bit but I'll notify you again.

**Comment by p32929** [comment]
As long as my new portfolio is listed, I'm more than happy about it :)
You don't have to delete anything if it requires more work.
BTW, thanks...
