### ISSUE TITLE
I am not able to Find My Portfolio

### ISSUE THREAD

**Issue by JayantGoel001** [umihico/PortfolioHub#73]
Hi @umihico,
I was searching my portfolio but couldn't find mine.
`https://JayantGoel001.github.io/`

Plus It would be a great Idea to add a search bar where users can search for their portfolios.

Thanks

**Comment by umihico** [comment]
@JayantGoel001 
Thank you for sharing your issue.

I found your repository without tag `portfolio-website`.  After you tagged and a while, you'll find at least from [here](https://portfoliohub.umihi.co/?user=JayantGoel001)

You are right we need that function for visitors. (Or at least README to describe crawler logics, right? sorry.)
Can I ask how did you find my website if your's one is not listed? 

I'd like to keep this issue open until I made the function.

**Comment by umihico** [comment]
Did you make your website from scratch? It's really awesome BTW!

**Comment by JayantGoel001** [comment]
> @JayantGoel001 Thank you for sharing your issue.
> 
> I found your repository without tag `portfolio-website`. After you tagged and a while, you'll find at least from [here](https://portfoliohub.umihi.co/?user=JayantGoel001)
> 
> You are right we need that function for visitors. (Or at least README to describe crawler logics, right? sorry.) Can I ask how did you find my website if your's one is not listed?
> 
> I'd like to keep this issue open until I made the function.

I was just surfing GitHub and found your repo.😅

**Comment by JayantGoel001** [comment]
> Did you make your website from scratch? It's really awesome BTW!

I won't say from scratch but 80 - 90% I made on my own. (Just Took the structure of the portfolio.)🙂
Thanks btw.
